[WIP] Starring videonode
claptime/claptime pull request #23
Opened 2020-11-15 15:45 UTC by ThibautChamoux

TODO :
- rebase on develop
- lint
- proptypes
- control creation form

2020-11-16 14:00 UTC, ChristopheBougere requested changes

2020-11-16 14:00 UTC, ChristopheBougere commented on web/amplify/backend/api/claptimeapi/schema/models/VideoNode.graphql
> +  queries: { get: "getStarringVideoNode", list: "listStarringVideoNodes" },
pas l'impression que le get, list et update soient utilisés

2020-11-16 14:00 UTC, ChristopheBougere commented on web/amplify/backend/api/claptimeapi/schema/models/VideoNode.graphql
> +type StarringVideoNode
jusqu'ici on avait un fichier par `@model` donc peut être garder cette convention ?

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/molecules/StarringVideoNodeFormInput/index.jsx
> +    { resultPath: '$.listCollectionVideoNodes' },
il faudrait pas faire un getAll ici ? 🤔

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/Collection/StarringVideoNodesCarousel.jsx
> +        <StarringVideoNode starringVideoNode={i} />
missing key prop

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/StarringVideoNode/index.jsx
> +                  text="Plus d'infos"
i18n

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/StarringVideoNode/index.jsx
> +          {type === 'FILM' && (
pas les séries ?

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/graphql/types.js
> +  starringVideoNodes {
ce serait pas mal d'utiliser le système de Connection ici. d'ailleurs est-ce que le field `starringVideoNodes` ne devrait pas plutôt être en level COMPLETE ?

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/StarringVideoNode/index.jsx
> +              <Link href="/video/[video]" as={`/video/${id}`}>
Avec le `<Link>` de next js, il faut mettre un `<a>` en children

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/pages/collection/[collection]/edit/index.jsx
> +              <Form.Item
Il y a un gros blanc entre le bloc "à l'affiche" et les catégories chez moi:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/1325474/99258579-11a12900-2819-11eb-9477-f38411eda78e.png">

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/pages/collection/[collection]/edit/index.jsx
> +              <Form.Item
Peut être aussi customiser le message/icône quand il n'y a pas de film à l'affiche
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1325474/99258718-457c4e80-2819-11eb-8332-b9abdc15a434.png">

2020-11-16 14:00 UTC, ChristopheBougere commented on translations/fr-FR/web.json
> +      "starringVideoNodeLabelTooltip": "Le film du mois",
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1325474/99258797-617ff000-2819-11eb-8171-f7d5536c493d.png">
Ce serait bien de préciser que c'est un exemple

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/pages/collection/[collection]/edit/index.jsx
> +    );
j'ai eu cette erreur en supprimant et recréant un item avec le même film, mais en sauvegardant une seule fois
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/1325474/99259281-0dc1d680-281a-11eb-9a41-368411d69c60.png">
je pense qu'il faudrait delete puis create dans cet ordre là plutôt

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/StarringVideoNode/index.jsx
> +const StarringVideoNode = ({ starringVideoNode }) => {
Responsive à gérer 😄
![Uploading image.png…]()

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/organisms/Collection/index.jsx
>        {collection.categories.map((category) => (
Je verrais bien les titres de catégories avec la même typo que le label des "à l'affiche" perso
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/1325474/99259653-9d678500-281a-11eb-8df4-db5cd117698f.png">

Et peut être réduire sa taille, pour que le nom de la collection reste important aussi

2020-11-16 14:00 UTC, ChristopheBougere commented on web/amplify/backend/api/claptimeapi/schema/models/VideoNode.graphql
> +
Ce serait bien de créer quelques fixtures pour ce model

2020-11-16 14:00 UTC, ChristopheBougere commented on web/amplify/backend/api/claptimeapi/schema/models/VideoNode.graphql
> +  { allow: private, provider: iam, operations: [create, delete, read, update] },
je pense pas que cette autorisation soit utile pour le moment ?
```
{ allow: private, provider: iam, operations: [create, delete, read, update] },
```

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/molecules/StarringVideoNodeFormInput/AddStarringVideoNodeForm.jsx
> +      id="category-add-form"
wrong id

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/molecules/StarringVideoNodeFormInput/AddStarringVideoNodeForm.jsx
> +        <Button type="primary" form="category-add-form" htmlType="submit">
wrong id

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/components/molecules/StarringVideoNodeFormInput/AddStarringVideoNodeForm.jsx
> +          {t('collection.edit.categoryAdd')}
wrong translation

2020-11-16 14:00 UTC, ChristopheBougere commented on web/src/pages/collection/[collection]/edit/index.jsx
> +    const asyncMutationExec = async (mutation, input) => {
je pense qu'il faudrait limiter à 10 max le nombre de films qu'on peut mettre à l'affiche, pour éviter d'avoir des problèmes de pagination (il me semble que 10 est la valeur par défaut qu'ils récupère sur les connection 1-N)

2020-11-16 17:07 UTC, ThibautChamoux commented on web/amplify/backend/api/claptimeapi/schema/models/VideoNode.graphql
> +  queries: { get: "getStarringVideoNode", list: "listStarringVideoNodes" },
Le update je ne l'utilise plus effectivement, et le get est en trop
Par contre le list est nécessaire pour le SSR (sans ça tu as une exception quand tu accèdes à la page /collection)

2020-11-21 12:38 UTC, ThibautChamoux commented on translations/fr-FR/web.json
> +      "starringVideoNodeLabelTooltip": "Le film du mois",
J'ai formatté le texte en italique, ça me semble suffisant ?

2020-11-21 17:29 UTC, ChristopheBougere commented on translations/fr-FR/web.json
> +      "starringVideoNodeLabelTooltip": "Le film du mois",
Je mettrais quelque chose comme :
> La raison de cette mise à l'affiche ("Le film du mois" par exemple)

2020-11-23 17:21 UTC, ThibautChamoux commented
stylizedVariant est toujours utilisé, notamment par le <VideoPlayer />

2020-12-02 11:06 UTC, ChristopheBougere approved these changes

2020-12-03 11:23 UTC, merged