Minor fixes
claptime/claptime pull request #40
Opened 2020-12-21 21:11 UTC by ThibautChamoux

Minor modification of collection's cards layout and display + other css reworks

2020-12-21 21:15 UTC, ThibautChamoux commented
Le "fade on scroll" sur la landing page semble un peu "poussif" en local, mais j'aimerais tester sur staging pour voir si le lag est moins présent

2020-12-22 08:16 UTC, ChristopheBougere requested changes

2020-12-22 08:16 UTC, ChristopheBougere commented on web/src/components/organisms/LandingOfflineSection/index.jsx
> +  window.addEventListener('scroll', () => {
J'ai eu cette erreur en allant sur `/about/project/manifest` depuis une autre page:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1325474/102865222-c260a080-4435-11eb-9511-749d379fe90a.png">
Ce serait mieux d'utiliser `useRef` aussi (ou une prop function dans `BackgroundContainer`) plutôt que`document.getElementById`

2020-12-22 09:44 UTC, ThibautChamoux commented on web/src/components/organisms/LandingOfflineSection/index.jsx
> +  window.addEventListener('scroll', () => {
fixed, en plus j'avais fait un truc dans ce genre initialement -_-'

2020-12-22 09:47 UTC, ChristopheBougere approved these changes

2020-12-22 09:52 UTC, merged